### ISSUE TITLE
Debug panel show one query (fetch cursor id = 0)

### ISSUE THREAD

**Issue by jafaripur** [yiisoft/yii2-mongodb#126]
All of runned query just show this query in debug panel:

### What do you get instead?
```
fetch cursor id = 0
```
### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | dev-master
| Yii MongoDB version    | dev-master
| MongoDB server version | 3.2
| PHP version            | 5.6
| Operating system       | Ubuntu 14.0.4

**Comment by cebe** [comment]
can you elaborate? I do not understand the problem

**Comment by jafaripur** [comment]
![screenshot from 2016-06-16 13 50 14](https://cloud.githubusercontent.com/assets/5066430/16111782/57e97348-33c9-11e6-8bd6-4941a3a843c0.png)

Check debug panel screenshot, always show one unknow query instead real several query.

**Comment by klimov-paul** [comment]
Resolved by commit c370013c913469bb4b9f5bc8ae7f95e7033e346d

**Comment by skworden** [comment]
My debug panel still shows this using version MongoDb 2.1.2.  

I'm also running php 7.0.1 and mongo version 3.2.7
